name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 sanic==18.12 sanic_compress sanic-cors semver
    - name: Lint with flake8
      run: |
        flake8 . --count --exit-zero --max-line-length=79 --statistics
    - name: Test proxy server
      run: |
        ./test.py
