name: Build and push images

on:
  push:
    tags:
    - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        uses: ilteoood/docker_buildx@master
        with:
          publish: true
          imageName: webthingsio/addon-proxy
          platform: linux/amd64,linux/arm/v7,linux/arm64
          tag: latest,${GITHUB_REF:11}
          dockerHubUser: ${{ secrets.DOCKER_HUB_USER }}
          dockerHubPassword: ${{ secrets.DOCKER_HUB_PASSWORD }}
